stages:
  - build  
  - acceptance

build_image:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Building docker image..."
    - docker build . -t ${DOCKER_IO_REGISTRY_IMAGE}:latest
    - echo "Logging in to Docker registry..."
    - echo ${DOCKER_IO_REGISTRY_PASSWORD} | docker login -u ${DOCKER_IO_REGISTRY_USER} --password-stdin ${DOCKER_IO_REGISTRY}
    - echo "Pushing docker image to registry..."
    - docker push ${DOCKER_IO_REGISTRY_IMAGE}:latest

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: ${DOCKER_IO_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
