stages:
  - build
  - docker
  - setup
  - test
  - acceptance

build_image:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Building docker image..."
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest

run_container:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Logging in to Docker registry..."
    - echo ${CI_JOB_TOKEN} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - echo "Executing container..."
    - docker run -d -p 9091:9091 --name car-pooling-candidate-DjhM2EyYjN ${CI_REGISTRY_IMAGE}:latest
    - echo "Container ready"
    - sleep 10 # wait 10 seconds for the container to be ready

setup_and_start:
  stage: setup
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Installing dependencies..."
    - docker exec car-pooling-candidate-DjhM2EyYjN composer install
    - echo "Migrating..."
    - docker exec car-pooling-candidate-DjhM2EyYjN php artisan migrate
    - echo "Starting the worker..."
    - docker exec -d car-pooling-candidate-DjhM2EyYjN php /var/www/html/artisan queue:work --sleep=3 --tries=3    

run_tests:
  stage: test
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Ejecutando pruebas de PHPUnit..."
    - docker exec car-pooling-candidate-DjhM2EyYjN vendor/bin/phpunit --configuration /var/www/html/phpunit.xml

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
